codingtest-repository/codingtest

심소민/백준/11403.py, 심소민/백준/1439.py, 심소민/백준/9935.py
- **[1439] 뒤집기 (Silver 5):** 그리디 - 0->1 또는 1->0 으로 변경되는 구간을 count하여 절반으로 나눈 값을 올림하여 print. 0과 1을 뒤집을 수도 있기 때문에 변경되는 구간을 세는 게 편할 것 같다고 판단함.
- **[9935] 문자열 폭발 (Gold 4):** 스택- 스택의 마지막 부분이 폭발 문자열과 일치하면 제거, 처음에 문자열로 했다가 시간 초과 발생. 스택에 push 하는 부분이 문자열일 때 O(n)시간과 같다는 이유임을 알게 됨.
- **[11403] 경로찾기 (Silver 1):** 플로이드-워셜 알고리즘으로 탐색
아이디어가 떠오르지 않아 남의 코드로 공부함.. 2주 후 다시 풀어보겠습니다
- **무지의 먹방 라이브(Lv4)** 
- **[2661] 좋은 수열 (Gold 4)**
=> Feat: [1주차] 심소민 PR

이유영/백준/[11403]경로찾기.py, 이유영/백준/[1439]뒤집기.py, 이유영/백준/[2661]좋은수열.py, 이유영/백준/[9935]문자열폭발.py
- **[1439] 뒤집기 (Silver 5)**: 그리디 - 연속된 0/1 뭉텅이 개수 비교해서, 그 count가 더 적은 걸 return
- **[9935] 문자열 폭발 (Gold 4)**: 스택 - 폭발할 문자열과 스택에 집어넣은 문자열 역순 비교해서 pop
- **[2661] 좋은 수열 (Gold 4)**: 백트래킹 - 1, 2, 3을 차례로 덧붙여서 좋은 수열인지(전체 길이의 절반까지 중복 확인) 검사
- **[11403] 경로찾기 (Silver 1)**: 플로이드워셜
- 무지의 먹방 라이브는 떠오르는 해결책이 없어서 해결하지 못했습니다
=> [1주차] 이유영 PR

jwj/week01/[11403] 경로 찾기.py, jwj/week01/[1439] 뒤집기.py, jwj/week01/[2661] 좋은 수열.py, jwj/week01/[9935] 문자열 폭발.py, jwj/week01/[프로그래머스] 무지의 먹방 라이브.py
> 처음 `check()` 함수를 구현할 때, 앞에서부터 시작하여 이전 문자열과 비교 문자열을 비교해 같으면 나쁜 수열로 체크하고 다르면 for문의 끝까지 돌리도록 했으나 이 방법이 맞지 않았습니다. `backtracking()` 함수에서 리스트의 뒤에 원소가 추가되기 때문에 뒤에서부터 탐색을 해야겠다고 생각하여 `check()` 함수의 탐색 순서를 뒤에서부터 시작하도록 하여 해결하였습니다.
> 플로이드 워셜 알고리즘을 사용하여 모든 정점에서 모든 정점으로 가는 길이 존재하는지를 체크했습니다.
> 그리디 알고리즘이었습니다. 맨 처음 등장하는 문자를 카운팅하고 그 이후부터 for문을 돌려 0을 1로, 1을 0으로 바꾸는 카운팅을 반영하여 둘 중 최솟값을 구하는 방법으로 해결했습니다.
> 스택 자료구조를 활용했습니다. for문으로 문자 하나하나를 스택에 넣은 후 슬라이싱을 활용하여 폭발 문자열과 부분 문자열을 비교해 일치하면 부분 문자열의 길이만큼을 for문으로 돌려 스택에서 문자를 빼는 방식으로 해결했습니다. `Python3`에서는 시간초과가 나와 `PyPy3`로 바꿔 해결했습니다.
> 주어진 입력값을 분석해보면 그리디 형태지만 선형 탐색이 아닌 최소힙을 사용하는 우선순위 큐 문제임을 알 수 있었습니다. 문제에서 우선순위로 둘 요소는 음식 번호이며 이 인덱스를 별도로 관리하기 위해 `enumerate()`를 활용했고 k초 이내 범위에서 먹방이 계속 되도록 무한 반복하고 빠져나온 상태에서 남아 있는 힙의 원소를 람다식을 활용하여 음식 번호 순서대로 오름차순으로 정렬 후 다시 섭취해야할 음식 번호를 구하는 …
=> Feat: [1주차] 장우진 PR

이유영/백준/[15683]감시.py, 이유영/백준/[22942]데이터체커.py, 이유영/백준/[5639]이진검색트리.py, 이유영/백준/[9934]완전이진트리.py
교접하지 않고 원들이 나열된 경우, 스택을 충족한다는 점 활용하는 문제
<접근>
- N의 최대 개수를 고려했을 때 브루트포스로 접근할 수 없다고 판단
- 스택 활용하는 방법이 바로 떠오르지 않아서 풀이의 아이디어 참고
주어진 배열 기준으로, 이진 검색 트리의 특성 활용 + 전위 순회 특성 고려하여 root / left tree / right tree 구분 가능하다는 포인트 활용하는 문제
<접근>
- 주어진 배열로 핵심 아이디어 접근 X -> 풀이 참고
- 초기에 배열 슬라이싱 활용했다가 시간초과로 start, end 지점 넘기는 방식으로 수정하여 통과
주어진 배열 기준으로, 전위 순회의 특성을 고려하여 left tree / root / right tree로 구분 가능하다는 점 활용, 이를 레벨별로 출력하기 위해 queue 활용
브루트포스로 사각지대를 최소화할 수 있는 조합 찾기
=> [Feat]: 2주차 이유영 PR

jwj/1주차 라이브코테/[2615] 오목.py, jwj/1주차 라이브코테/[3109] 빵집.py, jwj/2주차 라이브코테/[1005] ACM Craft.py
* 문제집에서 관리하는 것이 조금 불편하다고 느껴져 제 이름 디렉터리 하위에 문제 출처와 풀이 답안만 공유합니다.
* 제 풀이가 정답은 아닙니다. 그냥 이런 답안도 있구나에 초점을 맞추셔서 참고용으로만 봐주시면 될 것 같습니다.
10.05 1주차 라이브 코딩테스트 문제 : 3109번(빵집), 2615번(오목)
10.12 2주차 라이브 코딩테스트 문제 : 1005번(ACM Craft)
=> 10.05, 10.12 실시했던 라이브 코딩테스트 문제들

심소민/백준/11053.py, 심소민/백준/1158.py, 심소민/백준/1316.py, 심소민/백준/17298.py, 심소민/백준/2175.py
[2178] 미로 탐색: BFS를 사용해 (0, 0)에서 시작해 도착점까지의 최단 경로를 찾음.
[1316] 그룹 단어 체커: 집합과 이전 문자 상태를 활용해 문자의 연속 여부를 검사, 중복 발생 시 그룹 단어가 아님을 판별.
[1158] 요새푸스 문제: 리스트와 인덱스를 이용해 사람을 순서대로 제거하고, 제거된 순서를 결과 리스트에 저장.
[11053] 가장 긴 증가하는 부분 수열(LIS): 동적 계획법(DP)을 사용해 각 위치에서 끝나는 증가 부분 수열의 최대 길이를 계산하고, 그 중 최댓값을 찾음.
[17298] 오큰수: 스택을 사용해 오른쪽에 위치한 더 큰 수를 효율적으로 찾으며, 각 원소에 대해 오큰수를 계산. 
*단순 반복문을 사용하면 시간 초과가 발생해 스택을 활용한 최적화가 필요했음
=> Feat: [3주차] 심소민 PR

jwj/week03/[11053] 가장 긴 증가하는 부분 수열.py, jwj/week03/[1158] 요세푸스 문제.py, jwj/week03/[1316] 그룹 단어 체커.py, jwj/week03/[17298] 오큰수.py, jwj/week03/[2178] 미로 탐색.py
> BFS 문제였습니다. 이동할 수 없는 칸과 이동할 수 있는 칸을 잘 비교하여 이동이 가능하다면 큐에 좌표를 넣어 큐에 들어있는 좌표가 없을 때까지 무한 반복하여 (N, M)의 위치로 이동시키는 방법으로 해결했습니다.
> 문자열을 다루는 문제였습니다. 해당 문자가 연속적으로 나타나는 경우만 가능하며 한 번 나온 문자가 이후에 불연속적으로 나타나는 경우만 체크해주면 되는 문제였습니다. 슬라이싱을 사용하여 이 부분을 효율적으로 해결할 수 있었습니다.
> 자료구조 문제였습니다. 큐에 원소를 넣고 K번 주기로 계속 돌린 다음 맨 처음 원소를 출력하여 간단히 해결할 수 있었습니다. `popleft()`와 `append()`를 사용해서 구현했는데 파이썬에서 지원하는 메서드 중에서 `rotate()`를 사용하여 돌릴 수 있다는 부분도 알게 되었고 `join()` 메서드의 경우 문자열을 한 번에 합치는 역할을 하는데 이 때, 배열 내부의 원소가 int형인 경우 사용할 수 없어 결과 리스트에 저장할 때 문자로 변환하여 넣어야 하는 것을 배웠습니다.
> DP문제였습니다. 다만 다른 DP 문제들에 비해서 입력 조건이 상당히 유한 문제에 속했습니다. 최악의 경우를 계산해보면 수열 A의 크기가 1,000으로 2중 for문을 통해 원소를 비교해도 최악의 경우 1,000,000이 나오는데 실질적으로는 이보다 적은 값이기에 2중 for문으로 구할 수 있을 것이라고 생각해서 2중 for문과 `max()`를 사용해서 해결했습니다.
> 자료구조 문제였습니다. 스택이 비어있다면 원소를 넣고 스택에 원소가 있다면 조건을 만족시킬 때까지 연산을 …
=> Feat: [3주차] 장우진 PR

강태영/week4/14567.py
풀이한 문제: 선수과목(백준 1516.py)
위상정렬문제에서 그래프의 depth를 구해 결과를 내는 문제라 생각하고 풀었습니다.
------
개인 사정으로 인하여 시간 안에 모든 문제를 풀지 못하였습니다.
이외의 문제는 일요일 중에 풀이하여 마저 PR 하도록 하겠습니다!
=> FEAT: [4주차] 강태영 PR

jwj/week04/[12933] 오리.py, jwj/week04/[14567] 선수과목.py, jwj/week04/[1516] 게임 개발.py, jwj/week04/[2056] 작업.py, jwj/week04/[4396] 지뢰 찾기.py, jwj/week04/[4396] 지뢰.py
> 위상 정렬 문제였습니다. 입력에서 주어지는 선수 과목 조건 그대로 진입 차수에 저장하는 방식으로 비교적 수월하게 해결할 수 있었습니다.
> 위상 정렬과 다이나믹 프로그래밍이 결합된 형태의 문제였습니다.  각 작업은 선행 관계에 있는 작업들을 먼저 처리해야 처리할 수 있으므로 진입 차수에 저장하고 위상 정렬을 수행하는 방식으로 해결할 수 있었습니다.
> 위상 정렬 문제였습니다. 전략 시뮬레이션 게임에 나오는 테크 트리를 생각하면 충분히 쉽게 풀이를 떠올릴 수 있습니다. 이전에 풀었던 [작업] 문제와 유형이 비슷하여 금방 해결이 가능했습니다.
> 구현 문제였습니다. 상하좌우 및 대각선 방향의 방향 배열을 만들고 지뢰의 좌표를 먼저 기록하였습니다. 영역을 벗어나는 경우는 제외시키고 영역 내부의 점이 만약 지뢰 좌표에 해당한다면 자기 자신의 좌표를 기준으로 존재하는 지뢰의 개수를 추가시켜줘야 합니다. 또한 마지막으로 지뢰가 있는 칸을 눌렀다면 모든 지뢰 좌표들을 변경해주면 되는 방식으로 문제를 해결할 수 있었습니다,
> 구현 문제였습니다. `quack` 순서대로 울어야 하며 방문 여부와 울음 소리를 계속 트래킹을 해야하는 문제였습니다. 만약 idx값 즉, 울음 소리 트래킹 값이 5가 된다면 문제에서 주어진 순서 그대로를 지키면서 울었다는 뜻이 되므로 최소 오리 수에 카운팅을 해줘야 합니다. 그리고 마지막에 만약 idx가 0보다 큰 임의의 값(즉, 울다 만 경우)이거나 울음 소리 스펠링에 포함되지 않아 방문 여부를 체크할 수 없는 경우가 발생하는 경우 녹음이 불가능한 소리이기 때문에 -1을 출력하고 종료하는 …
=> Feat: [4주차] 장우진 PR

jwj/week05/[1260] DFS와 BFS.py, jwj/week05/[18312] 시각.py, jwj/week05/[2231] 분해합.py, jwj/week05/[22864] 피로도.py, jwj/week05/[2606] 바이러스.py
> 브루트 포스 탐색 문제였습니다. 24 x 60 x 60 = 86,400으로 1억보다도 한참 작은 값이기 때문에 3중 반복문을 돌려도 시간 초과가 발생하지 않을 것이라고 생각하고 코드를 작성하여 문제를 해결할 수 있었습니다.
> 브루트 포스 탐색 문제였습니다. 하루는 24시간이라고 제시가 되어있으므로 for문을 통해 전부 돌려 최대 처리량을 구할 수 있었습니다.
> 브루트 포스 탐색 문제였습니다. 최대 1,000,000까지 들어올 수 있고 길이를 따지자면 7이므로 최대 1,000,000 x 7 = 7,000,000이므로 2중 반복문을 돌려 문제를 해결할 수 있었습니다.
> BFS문제였습니다. 1번 컴퓨터부터 시작하여 인접한 컴퓨터들을 꺼내어 감염시키고 해당 컴퓨터와 인접한 컴퓨터들을 방문 여부를 체크하면서 계속 꺼내 큐가 빌 때까지 돌려 감염된 컴퓨터의 개수를 세어주었습니다. 이 때, 마지막에 1번 컴퓨터를 통해 웜 바이러스에 걸리는 컴퓨터 수를 출력하라고 했으므로 1번 컴퓨터 자기 자신은 제외시킨 후 답을 출력해야 합니다.
> BFS와 DFS문제였습니다. DFS의 경우 재귀 호출을, BFS의 경우 인접 행렬을 사용하여 문제를 해결할 수 있었습니다.
=> Feat: [5주차] 장우진 PR

이정훈/5주차/[18312] 시각.cpp, 이정훈/5주차/[2231] 분해합.cpp, 이정훈/5주차/[22864] 피로도.cpp, 이정훈/5주차/[2606] 바이러스.cpp
=> Feat: [5주차] 이정훈 PR (임시)

강태영/week5/[BAK]18312.py, 강태영/week5/[BAK]2231.py, 강태영/week5/[BAK]22864.py, 강태영/week5/[BAK]2606.py
=> Feat: [5주차] 강태영 PR

강병호/6week/[1912] 연속합.py, 강병호/6week/[1932] 정수 삼각형.py, 강병호/6week/[2167] 2차원 배열의 합.py
골드 문제들(1749, 9251)를 아직 풀지 못했습니다.. 더 고민해보고 너무 오래 걸리면 블로그 풀이라도 완전히 이해한 후 설명을 올려놓겠습니다..
=> Feat: [6주차] 강병호 PR (임시)

이정훈/.vscode/settings.json, 이정훈/6주차/[1749] 점수따먹기.cpp, 이정훈/6주차/[1912] 연속합.cpp, 이정훈/6주차/[1932] 정수 삼각형.cpp, 이정훈/6주차/[2167] 2차원 배열의 합.cpp, 이정훈/6주차/[9251] LCS.cpp
- #26
- [백준 1932 (Silver 1)](https://www.acmicpc.net/problem/1932)
- DP
- [백준 1912 (Silver 2)](https://www.acmicpc.net/problem/1912)
- DP
- [백준 9251 (Gold 5)](https://www.acmicpc.net/problem/9251)
- DP
- [백준 2167 (Silver 5)](https://www.acmicpc.net/problem/2167)
- DP
- [백준 1749 (Gold 4)](https://www.acmicpc.net/problem/1749)
- DP
=> Feat: [6주차] 이정훈 PR (임시)

이정훈/7주차/[14594] 동방 프로젝트 (Small).cpp, 이정훈/7주차/[16918] 봄버맨.cpp, 이정훈/7주차/[18429] 근손실.cpp, 이정훈/7주차/[20438] 출석체크.cpp, 이정훈/7주차/[21922] 학부 연구생 민상.cpp
문제 풀이 자체보다는 입출력 과정에서 시간 초과가 발생하여 해결하는데 애를 좀 먹었습니다.
C++에서 해결 방법은 아래와 같습니다.
1. 입출력 관련 코드 추가
- [sync_with_stdio(false), cin.tie(0) 쓰는 이유](https://dingcoding.tistory.com/62)
3. endl 대신 \n 사용
- [[C++] std::endl이 \n과 다른 점 - 출력버퍼 이해하기](https://yechoi.tistory.com/48)
=> Feat: [7주차] 이정훈 PR

강병호/7week/[14594] 동방 프로젝트(small).py, 강병호/7week/[16918] 봄버맨.py, 강병호/7week/[18429] 근손실.py, 강병호/7week/[20438] 출석체크.py, 강병호/7week/[21922] 학부 연구생 민상.py
골드 5 문제는 풀이가 안잡혀서 블로그 글 보고 작성하였습니다...
=> Feat: [7주차] 강병호 PR

jwj/week07/[14594] 동방 프로젝트(Small).py, jwj/week07/[16918] 봄버맨.py, jwj/week07/[18429] 근손실.py, jwj/week07/[20438] 출석체크.py
* 21922번 문제는 미해결 상태입니다.
* 주말까지 도전해서 다시 풀어서 PR에 남겨놓겠습니다.
=> Feat: [7주차] 장우진 PR

강병호/8week/1182_부분수열의 합.py, 강병호/8week/14888_연산자 끼워넣기.py, 강병호/8week/2294_동전 2.py, 강병호/8week/6443_에너그램.py
동전 2는 이전에 c++로 구현한 것이 있어서 그거 보고 다시 문제 바꿔 풀었습니다. 주석되어 있는 부분은 제가 다시 로직 고민하고 채워보겠습니다.
15485 퇴사 2는 해결하지 못했습니다... 추후에 블로그 글보면서 이해하고 제 코드로 변경해보겠습니다...
=> Feat: [8주차] 강병호 PR

하주영/week9/[11055] 가장 큰 증가하는 부분 수열.py, 하주영/week9/[1106] 호텔.py, 하주영/week9/[13549] 숨바꼭질 3.py, 하주영/week9/[14675] 단절점과 단절선.py
스스로 푼 문제
- 11055, 14675
스스로 풀지 못한 문제
- 1106, 13549
=> [Feat] : 하주영 9주차 PR

이정훈/9주차/[11055] 가장 큰 증가하는 부분 수열.cpp, 이정훈/9주차/[1106] 호텔.cpp
1106, 14675, 13549, 22858 미해결
> 가족 여행 때문에 마무리하지 못할 것 같습니다.
=> Feat: [9주차] 이정훈 PR

jwj/week09/[14675] 단절점과 단절선.py
- 취업에 성공해서 이번주부터 일하게 되었습니다. 일부 문제를 해결하지 못했습니다.
- 앞으로도 참여는 계속 하도록 하겠습니다.
=> [Feat] : 장우진 9주차 PR
